#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# umask
umask 0077

# Load dotfiles
for file in ~/.{aliases,extra}; do
	[ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

# rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init - zsh)"

# autojump
# source /usr/local/etc/profile.d/autojump.sh

# Go settings
export GOROOT=`go env GOROOT`
# GOPATH is set in .extra
export PATH=$PATH:$GOROOT/bin

# Remove no match error (HEAD^)
unsetopt nomatch

# Set editor
export EDITOR=vi
export VISUAL=vi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
